name: 'facebook_ads'
version: '0.6.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  facebook_ads:
    +schema: facebook_ads
    +materialized: table
    intermediate:
      +materialized: view

  version_2:
    +schema: version_2
    +materialized: table
    intermediate:
      +materialized: view

  facebook_ads_drug:
    +schema: facebook_ads_drug
    +materialized: table
    intermediate:
      +materialized: view
vars:

  facebook_ads_database: snowflake
  facebook_ads_schema: version_2

  facebook_ads:
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    url_tag: "{{ ref('stg_facebook_ads__url_tag') }}"
  version_2:
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    url_tag: "{{ ref('stg_facebook_ads__url_tag') }}"
  facebook_ads_drug:
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    url_tag: "{{ ref('stg_facebook_ads__url_tag') }}"
  snowflake_fb_ads:
    account_history: "{{ ref('stg_facebook_ads__account_history') }}"
    ad_history: "{{ ref('stg_facebook_ads__ad_history') }}"
    ad_set_history: "{{ ref('stg_facebook_ads__ad_set_history') }}"
    basic_ad: "{{ ref('stg_facebook_ads__basic_ad') }}"
    campaign_history: "{{ ref('stg_facebook_ads__campaign_history') }}"
    creative_history: "{{ ref('stg_facebook_ads__creative_history') }}"
    url_tag: "{{ ref('stg_facebook_ads__url_tag') }}"
